title: Harrison Williams
url: "https://harriswms.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/researcher/"
 - name: "CV"
   link: "files/cv.pdf"
# - name: "Contact"
#   link: "contact"
